version: '3.8'

services:
  # База данных
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: HelpDesk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ansar09595
    ports:
      - "5432:5432"

  # Приложение
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:ansar09595@db:5432/HelpDesk
      JWT_SECRET_KEY: your-secure-secret-key
    depends_on:
      - db
